### PR TITLE
Add Hasura Dashboard link

### PR DESCRIPTION
**Pull request by brijeshshah13**
Fixes: https://github.com/hasura/support/issues/424

### CODE REVIEW

**Review by shark-h — CHANGES_REQUESTED** [review]
The last line could have "you can also go to your [hasura dashboard](https://dashboard.hasura.io) and see the clusters available in your account."

**Comment by brijeshshah13** [comment]
@shark-h The note for the user to keep the cluster name in mind is for the use of opening the app URL. Although, if you still need me to change the statement, I can.

**Comment by shark-h** [comment]
@brijeshshah13 The note is fine at it's place. :)

**Comment by coco98** [comment]
@brijeshshah13 We're updating the nodejs-express README in fairly major way. We'll keep this PR open till we're done with the update. We'll come back to this then and merge if it is still required.

**Comment by brijeshshah13** [comment]
@coco98 Alright. No problem.

**Comment by brijeshshah13** [comment]
@coco98 Just for the record, I'm enrolled in HPDF. So, kindly let me know if this bug will be counted or not.

**Comment by praveenweb** [comment]
The README format has changed. Closing this PR.

**Pull request closed without merging**
